output "name_prefix" {
  description = "Resolved name prefix used across nested modules."
  value       = local.name_prefix
}

output "identity_id" {
  description = "Hex identity generated by the basic_identity module."
  value       = module.basic_identity.identity_id
}

output "identity_name" {
  description = "Pet name generated by the basic_identity module."
  value       = module.basic_identity.pet_name
}

output "content_path" {
  description = "Path to the primary content file created by basic_content."
  value       = module.basic_content.content_path
}

output "content_sha1" {
  description = "SHA1 of the primary content file."
  value       = module.basic_content.content_sha1
}

output "metadata_path" {
  description = "Path to the metadata file created by basic_content."
  value       = module.basic_content.metadata_path
}

output "summary_path" {
  description = "Path to the root summary JSON file."
  value       = local_file.root_summary.filename
}

output "bundle_marker_id" {
  description = "ID of the optional root null_resource bundle marker."
  value       = try(null_resource.bundle_marker[0].id, null)
}

output "common_labels" {
  description = "Labels applied across the test stack."
  value       = local.common_labels
}

output "multi_instance_count" {
  description = "Number of X instances created by the multi_instance nested module."
  value       = module.multi_instance.instance_count
}

output "multi_instance_keys" {
  description = "Keys of X instances created by the multi_instance nested module."
  value       = module.multi_instance.instance_keys
}

output "multi_instances" {
  description = "Full map of multi_instance X details (identity, pet, artifact path)."
  value       = module.multi_instance.instances
}

output "multi_identity_ids" {
  description = "Map of multi_instance key to identity id."
  value       = module.multi_instance.identity_ids
}
