variable "project_name" {
  description = "Base name used when composing resource identifiers."
  type        = string
  default     = "external-test"
}

variable "environment" {
  description = "Logical environment label applied to generated names and metadata."
  type        = string
  default     = "dev"
}

variable "name_separator" {
  description = "Separator inserted between name segments."
  type        = string
  default     = "-"
}

variable "identity_byte_length" {
  description = "Number of random bytes used by the nested identity module."
  type        = number
  default     = 4

  validation {
    condition     = var.identity_byte_length >= 2 && var.identity_byte_length <= 16
    error_message = "identity_byte_length must be between 2 and 16."
  }
}

variable "content_body" {
  description = "Primary body text written by the nested content module."
  type        = string
  default     = "Generated by Terraform.External.Test for offline module testing."
}

variable "output_directory" {
  description = "Directory where local artifact files are written."
  type        = string
  default     = "generated"
}

variable "enable_bundle_marker" {
  description = "When true, create a root-level null_resource marker tied to nested module outputs."
  type        = bool
  default     = true
}

variable "multi_instances" {
  description = "Map of instance keys for the multi_instance nested module (creates more than one instance of X)."
  type = map(object({
    label       = optional(string)
    pet_length  = optional(number, 2)
    byte_length = optional(number, 4)
  }))
  default = {
    "alpha"   = { label = "alpha", pet_length = 2 }
    "bravo"   = { label = "bravo", pet_length = 2 }
    "charlie" = { label = "charlie", pet_length = 3 }
  }
}
